core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("house_price.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

house_price/urls.py
from django.urls import path

from .views import HomeView, HousePricePredict

app_name = "house_price"
urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("house-price-predict/", HousePricePredict.as_view(), name="house-price-predict"),
]

house_price/models.py
from django.db import models

# Create your models here.

house_price/views.py
from django.shortcuts import render
from django.views import View
from django.http import JsonResponse
import pickle
import numpy as np
import os


class HomeView(View):
    def get(self, request):
        return render(request, "house_price/home.html")


class HousePricePredict(View):
    def post(self, request):
        house_area = request.POST.get("houseArea", None)
        total_rooms = request.POST.get("totalRooms", None)
        house_style = request.POST.get("houseStyle", None)
        total_bathrooms = request.POST.get("totalBathrooms", None)
        total_kitchens = request.POST.get("totalKitchens", None)
        total_fireplaces = request.POST.get("totalFireplaces", None)
        garage_area = request.POST.get("garageArea", None)
        car_capacity = request.POST.get("carCapacity", None)
        basement_area = request.POST.get("basementArea", None)
        pool_area = request.POST.get("poolArea", None)
        central_air = request.POST.get("centralAir", None)
        overall_qual = request.POST.get("overallQual", None)

        json_response = {}

        if house_area is not None or total_rooms is not None or house_style is not None or \
            total_bathrooms is not None or total_kitchens is not None or total_fireplaces is not None or \
            garage_area is not None or car_capacity is not None or basement_area is not None or \
            pool_area is not None or central_air is not None or overall_qual is not None:
            # Loading the linear regression model
            model_directory = f"{os.getcwd()}/house_price"
            model = pickle.load(open(f"{model_directory}/house_prediction_model.pkl", "rb"))

            # For HouseStyle
            # 1Story = 2
            # 2Story = 5
            # 1.5Fin = 0
            # SLvl = 7
            # SFoyer = 6
            # 1.5Unf = 1
            # 2.5Unf = 4
            # 2.5Fin = 3

            if house_style.lower() == "1story":
                house_style = 2
            elif house_style.lower() == "2story":
                house_style = 5
            elif house_style.lower() == "1.5fin":
                house_style = 0
            elif house_style.lower() == "slvl":
                house_style = 7
            elif house_style.lower() == "sfoyer":
                house_style = 6
            elif house_style.lower() == "1.5unf":
                house_style = 1
            elif house_style.lower() == "2.5unf":
                house_style = 4
            elif house_style.lower() == "2.5fin":
                house_style = 3

            if central_air.lower() == "yes":
                central_air = 1
            else:
                central_air = 0

            # For CentralAir
            # Y = 1
            # N = 0

            # Data serial -> house_area, total_rooms, total_bathrooms, total_kitchens, total_fireplaces, 
            # garage_area, car_capacity, basement_area, pool_area, overall_qual, house_style, central_air
            dataset = [
                [
                    float(house_area), int(total_rooms), int(total_bathrooms), int(total_kitchens), int(total_fireplaces), float(garage_area),
                    int(car_capacity), float(basement_area), float(pool_area), int(overall_qual), int(house_style), int(central_air)
                ]
            ]
            # print(dataset)

            result = np.round(model.predict(dataset))   # -> Returns a list
            # print(result)
            json_response = {
                "success": True,
                "result": result[0]
            }
        else:
            json_response = {
                "failed": True,
            }

        return JsonResponse(json_response, safe=False)

house_price/templates/house_price/home.html
{% extends "base.html" %}

{% load static %}

{% block content %}

{% comment %}Custom css + js{% endcomment %}
<link rel="stylesheet" href="{% static 'css/home.css' %}">
<script src="{% static 'js/home.js' %}" defer></script>

<div id="home__mainDiv" class="max-w-screen-2xl mx-auto w-full h-full flex flex-col items-center justify-center mt-10">
    <div id="home__cardDiv" class="w-[70%] bg-slate-200 shadow-lg rounded-lg flex flex-col items-center text-sm">
        <div class="flex justify-center">
            <img src="{% static 'images/house.jpg' %}" class="w-[7rem] h-[7rem] object-contain" alt="">
        </div>
        <div class="mb-5 text-center">
            <h3 class="font-semibold text-base lg:text-xl text-slate-800">House Price Prediction</h3>
        </div>

        <div id="error__msgDiv" class="hidden">
            <p class="text-sm text-rose-500 font-semibold">Error Message!</p>
        </div>

        <div id="house__predictionResultModal" class="max-w-screen-2xl mx-auto w-full h-full fixed top-0 left-0">
            <div class="px-5 py-16 w-[80%] lg:w-1/2 rounded-lg shadow-lg absolute top-[50%] left-[50%] z-50 bg-slate-200 flex flex-col items-center gap-y-5">
                <div class="absolute right-1.5 top-1.5">
                    <section id="close__predictionModal" class="cursor-pointer hover:text-rose-500 text-slate-600">
                        <span class="iconify text-xl" data-icon="ep:circle-close"></span>
                    </section>
                </div>
                <h5 class="text-slate-800 font-semibold text-base lg:text-xl">Predicted Result</h5>
                <p class="text-slate-600">House Predicted Price is <span class="font-semibold" id="predicted__result"></span></p>
            </div>
        </div>

        {% include "house_price/predict_form.html" %}
    </div>
</div>

{% endblock %}

house_price/templates/house_price/predict_form.html
<form method="POST" action="{% url 'house_price:house-price-predict' %}" id="home__form" class="flex flex-col justify-between h-full w-full px-5 mt-5">
    {% csrf_token %}
    <div class="grid grid-cols-3 gap-x-5 gap-y-3">
        <div class="flex flex-col items-start justify-start flex-1 relative z-0 w-full mb-5 group">
            <input type="number" id="house_area" name="house_area" class="text-slate-700 block py-2.5 px-0 w-full text-sm bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-indigo-400 peer" placeholder=" " required />
            <label for="house_area" class="text-slate-800 peer-focus:font-medium absolute text-sm duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-indigo-400 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Area of the House <span class="text-slate-500">(Square Feet)</span></label>
        </div>
        <div class="flex flex-1 relative z-0 w-full mb-5 group">
            <input type="text" id="total_rooms" name="total_rooms" class="text-slate-700 block py-2.5 px-0 w-full text-sm bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-indigo-400 peer" placeholder=" " required />
            <label for="total_rooms" class="text-slate-800 peer-focus:font-medium absolute text-sm duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-indigo-400 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Number of Rooms</label>
        </div>
        <div class="mb-3">
            <select id="house_style" class="form-select appearance-none
              block
              w-full
              py-2.5
              text-sm
              font-normal
              text-slate-800
              bg-transparent bg-clip-padding bg-no-repeat
              border-b-2 border-solid border-gray-300
              rounded
              transition
              ease-in-out
              m-0
              focus:text-slate-700 focus:bg-white focus:border-indigo-400 focus:outline-none custom__select" aria-label="Default select example" required>
                <option selected value="">Select House Style</option>
                <option value="1Story">1Story</option>
                <option value="2Story">2Story</option>
                <option value="1.5Fin">1.5Fin</option>
                <option value="Slvl">SLvl</option>
                <option value="SFoyer">SFoyer</option>
                <option value="1.5Unf">1.5Unf</option>
                <option value="2.5Unf">2.5Unf</option>
                <option value="2.5Fin">2.5Fin</option>
            </select>
        </div>

        <div class="flex flex-1 relative z-0 w-full mb-5 group">
            <input type="text" id="total_bathrooms" name="total_bathrooms" class="text-slate-700 block py-2.5 px-0 w-full text-sm bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-indigo-400 peer" placeholder=" " required />
            <label for="total_bathrooms" class="text-slate-800 peer-focus:font-medium absolute text-sm duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-indigo-400 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Number of Bathrooms</label>
        </div>
        <div class="flex flex-1 relative z-0 w-full mb-5 group">
            <input type="number" id="total_kitchens" name="total_kitchens" class="text-slate-700 block py-2.5 px-0 w-full text-sm bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-indigo-400 peer" placeholder=" " required />
            <label for="total_kitchens" class="text-slate-800 peer-focus:font-medium absolute text-sm duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-indigo-400 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Number of Kitchens</label>
        </div>
        <div class="flex flex-1 relative z-0 w-full mb-5 group">
            <input type="text" id="total_fireplaces" name="total_fireplaces" class="text-slate-700 block py-2.5 px-0 w-full text-sm bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-indigo-400 peer" placeholder=" " required />
            <label for="total_fireplaces" class="text-slate-800 peer-focus:font-medium absolute text-sm duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-indigo-400 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Number of Fireplaces</label>
        </div>

        <div class="flex flex-1 relative z-0 w-full mb-5 group">
            <input type="text" id="garage_area" name="garage_area" class="text-slate-700 block py-2.5 px-0 w-full text-sm bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-indigo-400 peer" placeholder=" " required />
            <label for="garage_area" class="text-slate-800 peer-focus:font-medium absolute text-sm duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-indigo-400 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Area of the Garage</label>
        </div>
        <div class="flex flex-1 relative z-0 w-full mb-5 group">
            <input type="text" id="car_capacity" name="car_capacity" class="text-slate-700 block py-2.5 px-0 w-full text-sm bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-indigo-400 peer" placeholder=" " required />
            <label for="car_capacity" class="text-slate-800 peer-focus:font-medium absolute text-sm duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-indigo-400 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Car Capacity in the Garage</label>
        </div>
        <div class="flex flex-1 relative z-0 w-full mb-5 group">
            <input type="text" id="basement_area" name="basement_area" class="text-slate-700 block py-2.5 px-0 w-full text-sm bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-indigo-400 peer" placeholder=" " required />
            <label for="basement_area" class="text-slate-800 peer-focus:font-medium absolute text-sm duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-indigo-400 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Area of the Basement <span class="text-slate-500">(Square Feet)</span></label>
            <p class="absolute top-[120%] left-0 text-xs font-medium text-slate-600">Type 0 if does not have any basement</p>
        </div>

        <div class="flex flex-1 relative z-0 w-full my-5 group pool__areaDiv">
            <input type="text" id="pool_area" name="pool_area" class="text-slate-700 block py-2.5 px-0 w-full text-sm bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-indigo-400 peer" placeholder=" " required />
            <label for="pool_area" class="text-slate-800 peer-focus:font-medium absolute text-sm duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-indigo-400 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Area of the Pool <span class="text-slate-500">(Square Feet)</span></label>
            <p class="absolute top-[120%] left-0 text-xs font-medium text-slate-600">Type 0 if does not have any pool</p>
        </div>
        <div class="mb-3 mt-5">
            <select id="central_air" class="form-select appearance-none
              block
              w-full
              py-2.5
              text-sm
              font-normal
              text-slate-800
              bg-transparent bg-clip-padding bg-no-repeat
              border-b-2 border-solid border-gray-300
              rounded
              transition
              ease-in-out
              m-0
              focus:text-slate-700 focus:bg-white focus:border-indigo-400 focus:outline-none custom__select" aria-label="Default select example" required>
                <option selected value="">Has Central Air Condition?</option>
                <option value="yes">Yes</option>
                <option value="no">No</option>
            </select>
        </div>
        <div class="mb-3 mt-5">
            <select id="overall_quality" class="form-select appearance-none
              block
              w-full
              py-2.5
              text-sm
              font-normal
              text-slate-800
              bg-transparent bg-clip-padding bg-no-repeat
              border-b-2 border-solid border-gray-300
              rounded
              transition
              ease-in-out
              m-0
              focus:text-slate-700 focus:bg-white focus:border-indigo-400 focus:outline-none custom__select" aria-label="Default select example" required>
                <option selected value="">Overall Material & Finish Quality</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
                <option value="6">6</option>
                <option value="7">7</option>
                <option value="8">8</option>
                <option value="9">9</option>
                <option value="10">10</option>
            </select>
        </div>
    </div>

    <div class="flex justify-center mt-7 mb-5">
        <button type="submit" id="submit__button" class="flex items-center gap-x-2 rounded font-medium text-slate-200 bg-indigo-500 cursor-pointer border-0 outline-none hover:shadow-lg px-16 py-2.5 transition-0.3s duration-300 ease-in-out ripple__button">
            Predict 
                <div id="button__loader" class="hidden">
                    <span class="iconify text-base" data-icon="icomoon-free:spinner9"></span>
                </div>
        </button>
    </div>
</form>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>House Price Prediction</title>

    {% comment %}Tailwind{% endcomment %}
    <script src="https://cdn.tailwindcss.com" defer></script>
    {% comment %}Iconify{% endcomment %}
    <script src="https://code.iconify.design/2/2.2.1/iconify.min.js" defer></script>
</head>
<body>
    {% block content %}{% endblock %}

    {% comment %}Footer{% endcomment %}
    {% include "footer.html" %}
</body>
</html>

templates/footer.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/footer.css' %}">

<div id="footer" class="flex flex-col items-center gap-y-1.5 text-sm text-slate-800 w-full p-5 bg-slate-200 mt-10">
    <div class="flex justify-center gap-1 text-slate-600">
        &copy; Created By <a href="http://saminportfolio.pythonanywhere.com/" target="_blank" class="font-semibold text-slate-800 hover:underline">Wasek Samin</a>
    </div>
    <div class="text-slate-600">
        All Rights Reserved | 2022
    </div>
</div>